### ISSUE TITLE
Java-based utilities fail when using native Java

### ISSUE THREAD

**Issue by aLostEngineer** [USF-HII-Ops/HLA-deploy#1]
When running IDT test, the test will fail due to incorrect JAVA_HOME being exported. Currently added a flag (off by default) to enable using native binaries; don't use this.

**Comment by countdigi** [comment]
IMO it is better to use a custom java u dl in all cases - I would just close this after removing it from the code as an option - good call on an off by default flag though but wouldn't waste your time with _this_ particular project but maybe good idea for another.

**Comment by aLostEngineer** [comment]
Sounds good, especially since there's no portable way to instantiate `JAVA_HOME`. I'll remove the flag and refactor.

**Comment by aLostEngineer** [comment]
fixed in 63c41480bc182cb5ab900707095df540ec1982dd
